export { useGetAllApplications, APPLICATIONS_QUERY_KEYS } from './useGetAllApplications'
export { useGetApplicationById } from './useGetApplicationById'
export { useAddApplication } from './useAddApplication'
export { useUpdateApplication } from './useUpdateApplication'
export { useDeleteApplication } from './useDeleteApplication'
